server:
  port: 9200
spring:
  application:
    name: open-auth-gateway
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name:  com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/boot_security?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
      filters: stat,wall
  redis:
################### redis 单机版 start ########################## 
    host: 127.0.0.1
    port: 6379    
    timeout: 3000
    database: 1
################### redis 单机版 end ##########################   
#    cluster:
#      nodes: 192.168.3.157:7000,192.168.3.158:7000,192.168.3.159:7000,192.168.3.157:7001,192.168.3.158:7001,192.168.3.159:7001
##        #130.75.131.237:7000,130.75.131.238:7000,130.75.131.239:7000,130.75.131.237:7001,130.75.131.238:7001,130.75.131.239:7001
#        #192.168.3.157:7000,192.168.3.158:7000,192.168.3.159:7000,192.168.3.157:7001,192.168.3.158:7001,192.168.3.159:7001
#    timeout: 1000 # 连接超时时间（毫秒）
#    pool:
#      max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 8     # 连接池中的最大空闲连接
#      min-idle: 2     # 连接池中的最小空闲连接
#      max-wait: 100   # 连接池最大阻塞等待时间（使用负值表示没有限制）       
    
docker:
  ipAddress: 47.94.252.160

mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:com/open/**/dao/*.xml  


security:
  oauth2:
    token:
      store:
        type: redis


#设置最大超时时间
ribbon:  
  httpclient:
    enabled: false
  okhttp:
    enabled: true  
  ReadTimeout: 90000  
  ConnectTimeout: 90000 


#设置最大容错超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false    #设置熔断的超时时间开启 false关闭熔断功能，true开启熔断功能
        isolation:
          thread:
            timeoutInMilliseconds: 90000

 
zuul:
  retryable: false    #关闭重试
  sensitive-headers: #/oauth/token需要请求头处理
  add-host-header: true
  routes:
    baidu:  
      path: /test163/**
      url: http://www.163.com 
    auth:  
      path: /auth/**
      service-id: open-auth-server 
      strip-prefix: false   
      custom-sensitive-headers: true  #http://blog.didispace.com/spring-cloud-zuul-cookie-redirect/ zuul授权码跳转问题
    client:  
      path: /client/**
      service-id: open-eureka-client
      strip-prefix: false  
    auth_client: 
      path: /auth-client/**
      service-id: open-auth-client
      strip-prefix: true   
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    #注册实例文档
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号

  


  
 