server:  
  port: 9998  
spring:  
  application:  
    name: open-admin-server
  boot:  
    admin:
      routes:  
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        #,unieap-eureka-server-single
        location: turbine
eureka:  
  client:  
    serviceUrl:  
      defaultZone: http://127.0.0.1:1111/eureka/  
management:  
  security:  
    enabled: false